version: '3.4'

services:
  sftp-srv:
    image: atmoz/sftp
    volumes:
        # - /mnt/d/GenStore/sample-data-set/ddec-sample-files/ddec-converted-xml/clean:/home/admin/upload/raw:ro
        # - /mnt/d/GenStore/sample-data-set/ddec-sample-files/ddec/ddec/2020-10-05:/home/admin/upload/raw:ro
        - /mnt/c/data:/home/admin/app_root
        - ./:/home/admin/host
    ports:
        - "2222:22"
    networks:
      - microservice-network
    command: admin:devpwd:1001
  
  rabbit-queue:
    image: rabbitmq:3-management
    hostname: rabbit-1
    environment:
      - RABBITMQ_ERLANG_COOKIE='LabKey_Link_k1'
    ports:
      - '8081:15672'
      - '5672:5672'
    networks:
      - microservice-network
networks:
  microservice-network:
    external: true